[[redirects]]
from = "/api/*"
to = "https://backend-nodejs-production-79b3.up.railway.app/:splat"
status = 200
force = true
headers = {
  "X-Forwarded-Host" = "liceonosaradev.netlify.app"
}

[[redirects]]
from = "/ping"
to = "https://backend-nodejs-production-79b3.up.railway.app/ping"
status = 200
force = true
