import "./globals.css";
import { headers } from "next/headers";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Colegio Bocas de Nosara",
  description: "Generated by Next.js\nNosara dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
